name: "UMDU Home Assistant OS Updater"
description: "Add-on для обновления форка HAOS для umdu k1"
version: "0.9.0"
slug: "umdu_haos_updater"
init: false
arch:
  - aarch64
startup: services
boot: auto
host_dbus: true
hassio_api: true
hassio_role: admin
homeassistant_api: true
options:
  auto_update: false
  notifications: true
  debug: false
  dev_channel: false
  # MQTT настройки
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  auto_update: bool
  notifications: bool
  debug: bool
  dev_channel: bool
  # MQTT параметры
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: str?
map:
  - type: share
    read_only: false
services:
  - "mqtt:need"
