name: "UMDU Home Assistant OS Updater"
description: "Add-on для обновления форка HAOS для UMDU K1"
version: "0.6.6"
slug: "umdu_haos_updater"
init: false
arch:
  - aarch64
startup: services
boot: auto
host_dbus: true
hassio_api: true
hassio_role: admin
homeassistant_api: true
options:
  update_check_interval: 3600
  auto_update: false
  backup_before_update: true
  notifications: true
  mqtt_discovery: true
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  debug: false
schema:
  update_check_interval: int(300,86400)
  auto_update: bool
  backup_before_update: bool
  notifications: bool
  mqtt_discovery: bool
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: str?
  debug: bool
map:
  - type: share
    read_only: false
services:
  - "mqtt:need" 